### ISSUE TITLE
I'd be interested to know more about this project

### ISSUE THREAD

**Issue by GuillaumeRossolini** [darconeous/FlexPACS#1]
Hi,

I've found your door demo video and I was wondering if you would share the details of your implementation? I have a use case for this, especially if it is low cost (which it looks like it is).

You can reach me on Twitter @g_rossolini, my DMs are open.

Thanks & regards,

**Comment by darconeous** [comment]
This is one of my many projects that I have kicking around that has been punted to the back-burner. The idea was to convert my [shell-script based mechanism](https://github.com/darconeous/SimpleCardAuth) into a full-featured X.509-based PACS implementation. Other than coming up with the name and the intended behavior (all driven by x.509 cert architecture), I don't have anything to show for it yet.

Presumably once I get my house in order (Construction is taking way too long), I plan to come back around to this project, but it may be a year or more down the road given all of the other personal projects I have going on.

Sorry to disappoint.

On the other hand, I *DO* have a X.509-based NFC token PACS (run from an RPI) working at my house right now, using that [shell-script-based system](https://github.com/darconeous/SimpleCardAuth) I mentioned earlier. If you are suitably adventurous, you might be able to get that working. A few other people already have, amazingly.

**Comment by GuillaumeRossolini** [comment]
Oh there's no disappointment on my end, and thanks for taking the time to answer!
I am looking for options and your other project seems documented enough, I may give it a try (if I get funding for that door system).

Please feel free to close this fake issue any time.
Good luck with your Construction ;)
